base_address: http://192.168.30.5:5380
zones:
  home:
    domain: home.chesurah.net
    cnames: []
    a:
      - name: technitium
        ipv4: 192.168.30.5
      - name: vopnsense
        ipv4: 192.168.30.1
      - name: pve-pandora
        ipv4: 192.168.30.2
      - name: mikro-core
        ipv4: 192.168.30.3
      - name: mikro-srv
        ipv4: 192.168.30.4
      - name: mikro-hap
        ipv4: 192.168.33.2
      - name: home-assistant
        ipv4: 192.168.33.3
technitium_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39303233316133656661366162383966313434343637633062383164663466313763313139643763
          3666306165306431346461666335333535363138336138610a366265353335383137616234653561
          32353361326565313363313735643933313962343239336232643431356631303766373261363861
          3333383361393434390a643533643330336664366436643461343461313133383032383837633662
          65396562323566363066303439336235656131613334323634623438633063376161623562633436
          39393663633665633837663630306535326530613565383235363234306164306162643231386564
          35663266323337313565313264393265363239326237393230323263663431663364646330353434
          63656364313737383238
