proxmox_api_user: ansible-prov@pve
proxmox_api_host: 192.168.30.2
ansible_prov_token_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34643264333038303831313136633837346264323135633030373331303762323436356539396465
          3738616461616161306231383430326430353130386363660a636432303365633936343363653865
          37326262643637343833623334636232303638393336343234363333353837313731353561326635
          6435346265336465640a376135393337366163663830653037636165386534613664383135643362
          31303132393762326133366434356464663530663436613662383739333638663263343663346233
          3739396136623162623432373432356165613139636564626365
ansible_prov_token_id: ansible-prov@pve!ansible-prov-token
